# These are supported funding model platforms

github: momo5418

patreon:
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:

custom:
  - https://www.paypal.com/paypalme/mocntop
  - https://afdian.com/a/momo5418
